title: My coding blog
author: Görcsös Zoltán
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  CodeNinja blog 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
